-- First, remove the table if it exists
drop table if exists bookmarks_database;

-- Create the table anew
create table bookmarks_database (
    id integer primary key generated by default as identity,
    title text not null,
    url text not null,
    description text,
    rating integer not null
);

-- insert some test data
-- Using a multi-row insert statement here
insert into bookmarks_database (title, url, description, rating)
values
    ('google', 'https://www.google.com', 'where we find stuff', 5),
    ('Thinkful', 'https://www.thinkful.com', 'where I learn coding', 4),
    ('espn', 'https://espn.go.com', 'sports stuff', 4),
    ('freecodecamp', 'https://freecodecamp.com', 'where real coding learning takes place', 5),
    ('Bookmark 3', 'https://www.facebook.com', 'Social Media', 3),
    ('Bookmark 4', 'https://www.cnn.com', 'News', 4),
    ('Bookmark 5', 'https://www.bloc.com', 'School', 5);